// Cloudflare bindings (see wrangler.jsonc). `Env` comes from
// worker-configuration.d.ts, regenerated by `wrangler types` on postinstall.
declare global {
  namespace App {
    interface Platform {
      env: Env
      cf: CfProperties
      ctx: ExecutionContext
    }
  }
}

export {}
