name: Playwright Tests

on: [pull_request]

env:
  GITHUB_PR_NUMBER: ${{github.event.pull_request.number}}

jobs:
  prepare:
    name: Wait for Netlify deployment
    runs-on: ubuntu-latest
    steps:
      - name: Waiting for Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@v1.4
        id: wait-for-netlify-preview
        with:
          site_name: 'heffner'
          max_timeout: 180

  test:
    needs: prepare
    name: Run tests against PR environment
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: install dependencies
        run: npm ci
      - name: install playwright browsers
        run: npx playwright install --with-deps
      - name: run tests
        run: npm run test
        env:
          PLAYWRIGHT_TEST_BASE_URL: 'https://deploy-preview-${{env.GITHUB_PR_NUMBER}}--heffner.netlify.app/'
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
