name: Playwright Tests

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: voorhoede/get-netlify-url@v2
      id: get-netlify-url
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      env:
        SITE_URL: ${{ steps.get-netlify-url.outputs.url }}
      with:
        wait-on: ${{ steps.get-netlify-url.outputs.url }}
      run: npm run test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
